/**
 * @fileUpload
 * make file inputs pretty - adds "fake" input/button combo to disguise file upload widget
 * http://jsfiddle.net/aZeHz/
 * basic css you'll need:
 * these elements are generated by the javascripts
 * .IX_fileUpload { position: relative; }
 *
 * .IX_fileUpload .fake-field {
 *		background-color:#fff;
 *		overflow:hidden;
 *		position:absolute; top:0; left:0;
 *		z-index:1;
 * }
 *  .IX_fileUpload:hover { cursor:pointer; }
 *	.IX_fileUpload .fake-field input {
 *		width:300px;
 *	}
 * .IX_fileUpload .real-field {
 *		height:26px;
 *		filter:alpha(opacity: 0);
 *		opacity:0;
 *		position:relative;
 *		text-align:right;
 *		width:400px;
 *		z-index:2;
 * }
 *
 */
jQuery.IX_fileUpload = function(){
	var uniqueSuffix = 0;
	return jQuery('input[type=file]').each(function(){
		var $fileInput = jQuery(this),
			currentID = 'IX_fileUpload'+uniqueSuffix;

		$fileInput.addClass('real-field').wrap('<div id="'+currentID+'" class="IX_fileUpload"></div>');
		$wrapper= jQuery('#'+currentID);
		$fileInput.after('<div class="fake-field"><input type="text" /><a class="button">Browse</a></div>');
		$wrapper.find('.fake-field input').focus(function(e){ jQuery(this).blur(); });
		$fileInput.change(function(){
			$wrapper.find('.fake-field input').val(this.value).blur();
		});
	});
};